// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SevenHabitsTodoApp.Models;

namespace SevenHabitsTodoApp.Migrations
{
    [DbContext(typeof(TaskEntryContext))]
    partial class TaskEntryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("SevenHabitsTodoApp.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryID = 1,
                            CategoryName = "Home"
                        },
                        new
                        {
                            CategoryID = 2,
                            CategoryName = "School"
                        },
                        new
                        {
                            CategoryID = 3,
                            CategoryName = "Work"
                        },
                        new
                        {
                            CategoryID = 4,
                            CategoryName = "Church"
                        });
                });

            modelBuilder.Entity("SevenHabitsTodoApp.Models.TaskEntry", b =>
                {
                    b.Property<int>("TaskID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryID")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Completed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quadrant")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Task")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TaskID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Responses");

                    b.HasData(
                        new
                        {
                            TaskID = 1,
                            CategoryID = 2,
                            Completed = false,
                            DueDate = "2022-02-09",
                            Quadrant = 1,
                            Task = "Finish 455 MLR Project"
                        },
                        new
                        {
                            TaskID = 2,
                            CategoryID = 2,
                            Completed = false,
                            DueDate = "2022-02-11",
                            Quadrant = 2,
                            Task = "Wash Dishes"
                        },
                        new
                        {
                            TaskID = 3,
                            CategoryID = 1,
                            Completed = false,
                            DueDate = "2022-02-11",
                            Quadrant = 4,
                            Task = "Play Fortnite"
                        },
                        new
                        {
                            TaskID = 4,
                            CategoryID = 4,
                            Completed = true,
                            DueDate = "2022-02-06",
                            Quadrant = 2,
                            Task = "Do Ministering"
                        },
                        new
                        {
                            TaskID = 5,
                            CategoryID = 1,
                            Completed = false,
                            DueDate = "2022-02-09",
                            Quadrant = 3,
                            Task = "Call Mom back"
                        },
                        new
                        {
                            TaskID = 6,
                            CategoryID = 3,
                            Completed = false,
                            DueDate = "2022-02-12",
                            Quadrant = 1,
                            Task = "Deliver new report to manager"
                        },
                        new
                        {
                            TaskID = 7,
                            CategoryID = 2,
                            Completed = false,
                            DueDate = "2022-02-16",
                            Quadrant = 2,
                            Task = "Apply for graduation"
                        },
                        new
                        {
                            TaskID = 8,
                            CategoryID = 4,
                            Completed = false,
                            DueDate = "2022-02-13",
                            Quadrant = 2,
                            Task = "Go to church"
                        },
                        new
                        {
                            TaskID = 9,
                            CategoryID = 2,
                            Completed = false,
                            DueDate = "2022-02-09",
                            Quadrant = 1,
                            Task = "Finish Project 1"
                        },
                        new
                        {
                            TaskID = 10,
                            CategoryID = 1,
                            Completed = false,
                            DueDate = "2022-02-11",
                            Quadrant = 3,
                            Task = "Go grocery shopping"
                        });
                });

            modelBuilder.Entity("SevenHabitsTodoApp.Models.TaskEntry", b =>
                {
                    b.HasOne("SevenHabitsTodoApp.Models.Category", "CategoryName")
                        .WithMany()
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
